### ISSUE TITLE
using import_component for multiple inter-dependent components

### ISSUE THREAD

**Issue by martinjrobins** [MichaelClerx/myokit#875] opened 2022-05-17 15:56 UTC
I'm trying to use the `Model.import_component` function to import a collection of components that are inter-dependent in that each component references variables in other components. 

I'm a bit unsure on how to use `import_component` to do this, as importing a component that references variables in other components that have not been imported yet will fail. 

A partial solution (suggested by @Rebecca-Rumney) is to import all the variables into a temporary component, then import all the components, using a variable mapping to all the variables in the temporary component. But what is the best way to fix up the references to these temporary variables once you have imported all the components?

**Comment by martinjrobins** [comment] 2022-05-17 16:27
Perhaps I could 
1. import all the components, using the mapping to the temporary variables
2. loop through the components to be imported again, removing each in turn from the new model, then re-adding with no variable mapping this time

?? 

I'll give this a go and let you know.....

**Comment by MichaelClerx** [comment] 2022-05-17 16:37
Closing this as a duplicate of https://github.com/MichaelClerx/myokit/issues/806 :D :D :D

**Closed by MichaelClerx** 2022-05-17 16:37 UTC
